### ISSUE TITLE
Add downloads badge

### ISSUE THREAD

**Issue by alejandrofdez-us** [alejandrofdez-us/similarity-ts#3]
https://pepy.tech/projects/similarity-ts-cli?timeRange=threeMonths&category=version&includeCIDownloads=true&granularity=daily&viewType=chart&versions=1.0.1%2C1.0.0

[![PyPI Downloads](https://static.pepy.tech/badge/similarity-ts-cli)](https://pepy.tech/projects/similarity-ts-cli)

**Comment by felescgon** [comment]
Added badges to both similarity-ts and similarity-ts-cli repositories
